version: '3.8'
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: music_library_api
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/music_library
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
